### PR TITLE
Nicer introduction page

### PR DESCRIPTION
**Pull request by yogsototh**
I removed the subtitle from my preceding example. Now the introduction page should look a bit better.

### CODE REVIEW

**Comment by gregwebs** [comment]
thanks!

**Comment by gregwebs** [comment]
Instead of `<div .jumbotron>` you can just use `<.jumbotron>`. However, I am wondering if this should be using `<section>`

**Comment by yogsototh** [comment]
Thanks, I didn't knew that. And yes using `<section>` appears to be a good idea.

**Comment by MaxGabriel** [comment]
Hm, this PR appears to have removed the section on Yesod's JSON support

**Comment by gregwebs** [comment]
I made the semantic HTML change in #101. @yogsototh want to add the JSON part back in?

**Comment by yogsototh** [comment]
@gregwebs yes of course, I'll fix it ASAP

**Pull request merged**
