### PR TITLE
Document quoting numeric values

### PR DESCRIPTION
**Pull request by MaxGabriel**
See https://github.com/yesodweb/yesod/issues/1061

### CODE REVIEW

**Comment by MaxGabriel** [comment]
An alternate way to help people find this information would be for me to just open a stackoverflow question about this an answer it; imo that'd actually be better than mentioning it in the yaml file.

**Comment by creichert** [comment]
Looks good to me. I think it's okay to document it here as well. I wonder if this could be fixed in the yaml package. Thanks!

**Comment by MaxGabriel** [comment]
Not sure if this is too hacky, but could the database backends be modified to accept either a string or number (then convert the number to a string?). https://github.com/yesodweb/persistent/blob/b5b9e3ac6b69256f080db232ee387affd7fe6890/persistent-postgresql/Database/Persist/Postgresql.hs#L920

**Comment by snoyberg** [comment]
That would not work for passwords like "+123" or "123.000", which will be
rendered differently than they parse.

On Mon, Aug 24, 2015 at 8:33 PM, Maximilian Tagher <notifications@github.com

**Comment by MaxGabriel** [comment]
Good point

**Pull request merged**
