### PR TITLE
Postgres api

### PR DESCRIPTION
**Pull request by tippenein**
Opening this API-specific scaffold with seeds, makefile and some general examples for comment.

I used the handler examples from this (very nice) @pbrisbin post:
https://pbrisbin.com/posts/writing_json_apis_with_yesod/

I use this scaffold often enough that I'd like to make it generally useful here. Comments welcome!

### CODE REVIEW

**Comment by psibi** [comment]
Probably this should go inside a new template ?

Also is there any justification for changing the way it is now - Instead of externals `models` file - you are defining everything inside `Models.hs`, You seem to defining all the extensions in `package.yaml` file ?

**Comment by tippenein** [comment]
Yes. I intended this as a new template but diffed against `postgres` branch to show only the relevant changes. Sorry for the discrepancies, I copied most of this from another project of mine. 

I like your `yesod-rest` repo too, @psibi ! I would gladly use that as a template if it was provided here. I'm just looking for something with the server-side rendering removed and batteries included.

**Comment by psibi** [comment]
Nice! Can you revise your PR such that it obeys the established norms in the other templates.

Regarding, `yesod-rest`, the different is that it provides an API server as a subsite. So the master site is used for render HTML and the subsite is used for the REST layer communication. So, I would see a value in a template like this which you have created. :) Also feel free to integrate my template as a separate one here. I haven't got any spare time to do it, but it's on my todo list.

**Comment by tippenein** [comment]
I think yesod-rest pretty much provides everything needed and this addition doesn't seem to me to add enough benefit to be worth it. Also, I'm under the impression that most people will roll their own somewhat-specific api starter from yesod-postgres or some other template. Thanks for reviewing!

**Pull request closed without merging**
