### PR TITLE
Nicer example page rendering.

### PR DESCRIPTION
**Pull request by yogsototh**
The source is a bit harder to read, but the result is nicer IMHO.
If it is ok we might use the same file for other branches.

### CODE REVIEW

**Comment by MaxGabriel** [comment]
Would you mind sharing a screenshot of what the new page looks like?

Also, would you mind submitting this PR against the `postgres` branch? It has a few more updates to the homepage file, and updates made to it get cross applied to the other branches (`mongo`, `mysql` etc.)

**Comment by yogsototh** [comment]
It looks like that:

screen shot 2015-09-21 at 23 56 31

I'll do a pull request to the posgresql branch then. But may be tomorrow it is very late for me now. Best.

**Comment by MaxGabriel** [comment]
I think it looks great! The "By default it uses bootstrap 3" line is weirdly positioned imo—thoughts on centering it or dropping that line altogether?

I'll merge this whenever you submit to the `postgres` branch

**Comment by yogsototh** [comment]
I've removed the "By default it uses bootstrap 3" and made a pull request in the `postgres` branch. Best.

**Pull request closed without merging**
