### PR TITLE
no O2

### PR DESCRIPTION
**Pull request by gregwebs**
ghc manual recommends against this as a default

### CODE REVIEW

**Comment by snoyberg** [comment]
For an application I think this is still a better default. Do you have specific evidence to the contrary?

**Comment by gregwebs** [comment]
https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/options-optimise.html

> At the moment, -O2 is unlikely to produce better code than -O.

To me that indicates that I shouldn't turn it on without first benchmarking.

I haven't used O2 for a year. In my use cases compilation times slowing down deployment is a big issue and performance is always good enough that I cannot justify spending time benchmarking. When performance is looked at, it is usually for *load testing* to see how all the resource usage holds up. Generally there is greatest concern about DB interaction or GHC runtime behavior.

**Comment by snoyberg** [comment]
I'm sympathetic to the compile time issue. There definitely are cases where -O2 improves performance, especially with stream fusion in vector, and the -fdev flag is intended to help speed things up. But I don't feel this is important enough to spend more time on.

**Comment by gregwebs** [comment]
Thanks! I think those that stream-fuse vectors will quickly look to add `-O2`. Whereas most Haskell users (including myself a year ago) assume that O2 produces dramatic speedups, contrary to what is stated in the user guide.

**Pull request merged**
