### PR TITLE
Modernize the scaffolding

### PR DESCRIPTION
**Pull request by snoyberg**
(For some value of modernizing.)

* Move source files into the `src` dir
* Move language extensions into the Haskell files instead of cabal file

I think the first bullet is more important. I'm pretty much on the fence about the second, and wouldn't mind some feedback.

### CODE REVIEW

**Comment by MaxGabriel** [comment]
Would adding an hpack file be a good modernization move?

**Comment by snoyberg** [comment]
Funny you mention that... I started on that and then remembered that `yesod add-handler` would break. I'm kind of tempted to do it anyway, and then either:

1. Fix `add-handler`, or
2. Declare it dead

**Comment by bitemyapp** [comment]
Just chipping in some anecdata, I use hpack for all of my projects and I didn't know `yesod add-handler` existed.

**Comment by psibi** [comment]
While I do know that `add-handler` existed, I have never used the feature. But having `hpack` would be nicer. :)

**Comment by snoyberg** [comment]
I'm pretty strongly tempted to move the `yesod` binary down to just `devel` and `keter` commands. (And frankly, I'd personally be OK ditching `keter`, but I'm 99% certain a bunch of people are using it.)

I linked to this issue on Twitter, so hopefully anyone who is strongly attached to `add-handler` will find this and scream, otherwise let's move ahead. I'm going to push a commit meanwhile for hpack.

**Comment by MaxGabriel** [comment]
Why does it break `yesod add-handler`? I would have thought that `add-handler` just modified the cabal file (plus the .hs files), and the .cabal changes would then be overridden by hpack (and that's fine if your hpack file uses file globbing to add all your Handlers, instead of naming each individual one).

**Comment by enolan** [comment]
What's the argument in favor of `LANGUAGE` pragmas over the `default-extensions` field? For my view, I want less boilerplate at the top of every file, not more.

**Comment by snoyberg** [comment]
@MaxGabriel I didn't know about file globbing... I think that means problem solved. That's really awesome. Let me modify the commit to do that.

@enolan The arguments I hear are that it's more explicit, and works nicer with GHCi. I have no horse in this race, I have a slight personal preference for `default-extensions`.

**Comment by bitemyapp** [comment]
@snoyberg my preference is for `default-extensions`. I know the problem they are talking about and it can be worked around. Here's an example for HLint:

`hlint -XQuasiQuotes .`

Our Makefile at work that invokes `hlint` passes `-XQuasiQuotes` so that it is not reliant on the `LANGUAGE` pragma.

I do not know what people talking about ghci mean.

**Comment by chreekat** [comment]
> Our Makefile at work that invokes hlint passes -XQuasiQuotes so that it is not reliant on the LANGUAGE pragma.

To me this sounds like *more boilerplate*. +1 for in-file fields; I like the explicitness (just like explicit, per-module imports).

But I haven't scaffolded a yesod app in a while, so take that with a grain of salt. :)

**Comment by bitemyapp** [comment]
@chreekat I write the Makefile and list the extensions that could cause a parse error for HLint once

if I put the extensions in my modules, it's O(n) for the number of modules I have.

```
$ find . -name "*.hs" | wc -l
89
```

This is from one of 10-15 or so Yesod apps I've worked on, this one being an employer's. Can you explain how you calculating boilerplate here?

**Comment by chreekat** [comment]
I'm counting by number of technologies, number of tools that need to be
learned, and amount of implicit state/institutional knowledge baked into
the project.

I think boilerplate questions are often better solved in editors rather
than by adding a new layer of tech.

P.S. the "ghci problem" is that without inline pragmas you can't simply
"ghci $(file)" - you have to rely on other tools like Make or stack (which
does check default extensions, I think?) If one is relying on a lot of
other stack features, it's sort of a moot point (assuming the preceding
parenthetical is true).

P.p.s. I'm presenting all of this as someone without intense feelings on
the matter. :)

**Comment by snoyberg** [comment]
I'm still pretty strongly on the fence on this one, but given the unclear conclusions here, the Twitter poll favoring in-file extensions, and lots of previous complaints from people about default-extensions, I'm going to side on changing to in-file language pragmas. We can always switch back in the future.

**Pull request merged**
