### PR TITLE
Add a default=NULL to each Text Maybe column #144

### PR DESCRIPTION
**Pull request by vitalijzad**
It is linked to this issue: https://github.com/yesodweb/yesod-scaffold/issues/144

### CODE REVIEW

**Comment by snoyberg** [comment]
Thanks!

**Comment by snoyberg** [comment]
Does this require some lower bound on the persistent-mysql version? This change breaks with LTS 6: https://travis-ci.org/yesodweb/yesod-scaffold/jobs/221289742.

**Comment by vitalijzad** [comment]
Sorry, I didn't verify that.
Looks like persistent is mapping Haskell Text types into MySQL Text fields, wich have many resprictions, among them they cannot be null.
A way to solve this is specifying the MySQL field as varchar(255):

```
User
    ident Text sqltype=varchar(255)
    password Text Maybe sqltype=varchar(255) default=NULL
    UniqueUser ident
    deriving Typeable
Email
    email Text sqltype=varchar(255) 
    userId UserId Maybe default=NULL
    verkey Text Maybe default=NULL
    UniqueEmail email
Comment json -- Adding "json" causes ToJSON and FromJSON instances to be derived.
    message Text sqltype=varchar(255)
    userId UserId Maybe default=NULL
    deriving Eq
    deriving Show
```

If you agree with this solution, I will make a pull request.

**Comment by snoyberg** [comment]
I'm OK with that change, a PR would be great, thanks!

**Pull request merged**
