### PR TITLE
Add wrapper to non hompeage routes

### PR DESCRIPTION
**Pull request by amitaibu**
fixes #1398

**Login page**

log_in

**Error page**

not_found

**Home page**

welcome_to_yesod_

### CODE REVIEW

**Comment by amitaibu** [comment]
Pr also removes the special casing of the messages, by having a proper wrapper div on all (non-hompage) routes

**Comment by psibi** [comment]
@amitaibu In your snapshot, the login page div seems little off. Is that intended ?

**Comment by amitaibu** [comment]
No, it's the same line as the above message (container > row > col-md-12). It could be probably themed a little nicer, but I didn't want to try and do anything too fancy.

**Comment by psibi** [comment]
@amitaibu There seems to be merge conflict, can you fix that ? It would be also nice if the login form is also fixed!

**Comment by amitaibu** [comment]
>  It would be also nice if the login form is also fixed!

@psibi What do you mean by login form, do you mean something different from the login page (see the screenshots in the op)?

**Comment by psibi** [comment]
I meant the login page! Thanks for the patch.

**Pull request merged**
